name = "all"
kind = "marker-team"

[people]
leads = []
members = []
include-all-team-members = true

[[github]]
orgs = ["rust-lang"]

[[lists]]
address = "all@rust-lang.org"

[[lists]]
address = "team@rust-lang.org"

[[lists]]
address = "underhanded@rust-lang.org"
include-team-members = false
extra-emails = [
    "rust-underhanded@googlegroups.com",
]

[[lists]]
address = "verification@rust-lang.org"
include-team-members = false
extra-emails = [
    "rust-verification@googlegroups.com",
]

[[discord-roles]]
name = "WGs and Teams"

[[zulip-groups]]
name = "T-all"
excluded-people = [
    "adityac8",
    "andrewpollack",
    "arshiamufti",
    "badboy",
    "bdillo",
    "bnchi",
    "cdmistman",
    "celaus",
    "ericseppanen",
    "extrawurst",
    "flaki",
    "ibraheemdev",
    "KannanPalani57",
    "manyinsects",
    "mariannegoldin",
    "marioidival",
    "mattgathu",
    "opeolluwa",
    "sebasmagri",
    "SimonSapin",
    "spacekookie",
    "sunfishcode",
    "U007D",
    "wezm",
]
