name = "project-assumptions-on-binders"
kind = "project-group"
subteam-of = "types"

[people]
leads = ["BoxyUwU", "lcnr"]
members = [
    "BoxyUwU",
    "lcnr",
]
alumni = []

[website]
name = "Assumptions on Binders Project Group"
description = "Working to support where clauses on `for<'a>` in the Rust language"
repo = "https://github.com/rust-lang/project-assumptions-on-binders"
zulip-stream = "T-types/assumptions-on-binders"

[[github]]
orgs = ["rust-lang"]

[[zulip-groups]]
name = "project-assumptions-on-binders"

