name = "libs"
top-level = true

[people]
leads = [
    "Amanieu",
]
members = [
    "aapoalas",
    "adamgemmell",
    "Amanieu",
    "BurntSushi",
    "calebzulawski",
    "ChrisDenton",
    "clarfonthey",
    "cramertj",
    "cuviper",
    "Darksonn",
    "davidtwco",
    "dtolnay",
    "folkertdev",
    "hanna-kruppe",
    "ibraheemdev",
    "jhpratt",
    "joboet",
    "JohnTitor",
    "joshtriplett",
    "kennytm",
    "KodrAus",
    "LawnGnome",
    "Mark-Simulacrum",
    "m-ou-se",
    "nia-e",
    "Noratrieb",
    "programmerjake",
    "sayantn",
    "SimonSapin",
    "sunfishcode",
    "tgross35",
    "the8472",
    "thomcc",
    "workingjubilee",
    "yaahc",
]
alumni = [
    "alexcrichton",
    "aturon",
    "brson",
    "Gankra",
    "huonw",
    "Kimundi",
    "KodrAus",
    "LukasKalbertodt",
    "m-ou-se",
    "sfackler",
    "shepmaster",
    "SimonSapin",
    "withoutboats",
    "yaahc",
]

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[permissions]
perf = true
crater = true
dev-desktop = true
bors.rust.review = true

[website]
page = "library"
name = "Library team"
description = "Managing and maintaining the Rust standard library and official rust-lang crates"
zulip-stream = "t-libs"
repo = "https://github.com/rust-lang/libs-team"

[[lists]]
address = "libs-private@rust-lang.org"

[[lists]]
address = "libs@rust-lang.org"

[[lists]]
address = "libs-api@rust-lang.org"

[[lists]]
address = "library-team@rust-lang.org"

[[zulip-groups]]
name = "T-libs"

[[zulip-streams]]
# NOTE: should be renamed to t-libs/private, but non-urgent
name = "t-libs/reviewers"
