# People who are not members of Rust teams that have try/perf. permissions,
# but we nevertheless trust them with those permissions.
# This was established in https://github.com/rust-lang/leadership-council/issues/325.
name = "trusted-contributors"
kind = "marker-team"

[people]
leads = []
# Note: if you are a member of a Rust team that has permissions.bors.rust.try or
# permissions.perf set to true in its team toml file, then you do not need
# to be added to this list.
# For example, T-compiler and T-infra both have those permissions enabled.
# Project members who gain access to these permissions through other teams should be
# ideally removed from this team.
members = [
    "obi1kenobi",
    "scrabsha"
]
alumni = []

[permissions]
perf = true
bors.rust.try = true
