name = "wg-incr-comp"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["wesleywiser"]
members = ["davidtwco", "wesleywiser", "Aaron1011", "cjgillot"]
alumni = ["michaelwoerister", "pierwill", "pnkfelix", "spastorino"]

[[github]]
orgs = ["rust-lang"]

[website]
name = "Incremental compilation working area"
description = "Improving incremental compilation in rustc"
zulip-stream = "t-compiler/incremental"

[permissions]
perf = true
bors.rust.try = true
