name: Setup Rust
description: Install Rust stable toolchain and setup caching

runs:
  using: composite
  steps:
    - name: Install Rust Stable
      shell: bash
      run: |
        rustc -vV
        rustup update stable
        rustup default stable
        rustc -vV

    - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2.8.2
