name: Setup Rust
description: Install Rust stable toolchain and setup caching

runs:
  using: composite
  steps:
    - name: Install Rust Stable
      shell: bash
      run: |
        rustc -vV
        rustup update stable
        rustup default stable
        rustc -vV

    - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
