rules:
  github-app:
    disable: true
  dangerous-triggers:
    ignore:
      - dry-run.yml
  secrets-outside-env:
    ignore:
      - dry-run.yml
  concurrency-limits:
    ignore:
      - check-untracked-repos.yml
      - zizmor.yml
