allowed-mailing-lists-domains = [
    "rust-lang.org",
    "crates.io",
    "docs.rs",
    "rust-embedded.org",
    "rustconf.com",
]

allowed-github-orgs = [
    "rust-lang",
    "rust-lang-nursery",
    "rust-lang-deprecated",
    "rust-dev-tools",
    "rust-embedded",
    "rust-analyzer",
]

# GitHub organizations where member management is independent
# and should not be automatically synchronized
independent-github-orgs = [
    "rust-embedded",
]

permissions-bors-repos = [
    "bors-kindergarten",
    "rust",
]

permissions-bools = [
    "perf",
    "crater",
    "crates-io-admin",
    "dev-desktop",
    "sync-team-confirmation",
]

# GitHub accounts that are allowed to stay in the GitHub organizations,
# even if they may not be members of any team.
# Note: Infra admins are automatically included from the infra-admins team.
special-org-members = [
    # Bots.
    "bors",
    "craterbot",
    "rfcbot",
    "rust-rfcbot",
    "rust-embedded-bot",
    "rust-heroku-deploy-access",
    "rust-highfive",
    "rust-lang-core-team-agenda-bot",
    "rust-lang-glacier-bot",
    "rust-lang-owner",
    "rust-log-analyzer",
    "rust-timer",
    "rustbot",
    # Ferrous systems employees who manage the github sponsors
    # for rust-analyzer.
    "MissHolmes",
    "skade",
]

members-without-zulip-id = [
    "arshiamufti",
    "bnchi",
    "brotzeit",
    "celaus",
    "chris-morgan",
    "codesections",
    "da-x",
    "ecstatic-morse",
    "gdr-at-ms",
    "kennykerr",
    "mathk",
    "nico-abram",
    "opeolluwa",
    "patchfx",
    "pvdrz",
    "reitermarkus",
    "ryankurte",
    "Stammark",
    "therealprof",
    "zeenix",
    "abibroom",
    "rust-timer",
]

enable-rulesets-repos = [
   "rust-analyzer/expect-test",
   "rust-lang-nursery/rust-toolstate",
   "rust-lang/annotate-snippets-rs",
   "rust-lang/arewewebyet",
   "rust-lang/async-fundamentals-initiative",
   "rust-lang/backtrace-rs",
   "rust-lang/beyond-refs",
   "rust-lang/book",
   "rust-lang/bors",
   "rust-lang/calendar-generation",
   "rust-lang/calendar",
   "rust-lang/cargo-bisect-rustc",
   "rust-lang/cargo",
   "rust-lang/cc-rs",
   "rust-lang/ci-mirrors",
   "rust-lang/cmake-rs",
   "rust-lang/compiler-builtins",
   "rust-lang/compiler-team",
   "rust-lang/crater",
   "rust-lang/crates_io_og_image",
   "rust-lang/crates-build-env",
   "rust-lang/crates-io-auth-action",
   "rust-lang/crates.io",
   "rust-lang/docs.rs",
   "rust-lang/edition-guide",
   "rust-lang/ena",
   "rust-lang/flate2-rs",
   "rust-lang/fls",
   "rust-lang/futures-rs",
   "rust-lang/gha-self-hosted",
   "rust-lang/git2-rs",
   "rust-lang/gll",
   "rust-lang/glob",
   "rust-lang/hashbrown",
   "rust-lang/impl-trait-utils",
   "rust-lang/infra-smoke-tests",
   "rust-lang/josh-sync",
   "rust-lang/leadership-council",
   "rust-lang/libc",
   "rust-lang/llvm-project",
   "rust-lang/mdBook",
   "rust-lang/measureme",
   "rust-lang/miri",
   "rust-lang/miri-test-libstd",
   "rust-lang/nomicon",
   "rust-lang/odht",
   "rust-lang/portable-simd",
   "rust-lang/project-stable-mir",
   "rust-lang/project-exploit-mitigations",
   "rust-lang/reference",
   "rust-lang/rfcs",
   "rust-lang/rust-analyzer",
   "rust-lang/rust-bindgen",
   "rust-lang/rust-clippy",
   "rust-lang/rust-forge",
   "rust-lang/rust-log-analyzer",
   "rust-lang/rust-playground",
   "rust-lang/rustc_codegen_c",
   "rust-lang/rustc_codegen_gcc",
   "rust-lang/rustc-demangle",
   "rust-lang/rustc-dev-guide",
   "rust-lang/rustc-hash",
   "rust-lang/rustc-perf",
   "rust-lang/rustc-stable-hash",
   "rust-lang/rustfmt",
   "rust-lang/rustup",
   "rust-lang/simpleinfra",
   "rust-lang/socket2",
   "rust-lang/std-dev-guide",
   "rust-lang/stdarch",
   "rust-lang/team",
   "rust-lang/this-week-in-rust",
   "rust-lang/thorin",
   "rust-lang/triagebot",
   "rust-lang/wg-async",
   "rust-lang/wg-macros",
   "rust-lang/www.rust-lang.org",
]
