org = "rust-lang"
name = "arewewebyet"
description = "Are we web yet? A simple reckoning of Rust's readiness for Web-related things."
homepage = "https://www.arewewebyet.org/"
bots = []

[pages]
build-type = "legacy"
branch = "zola-build"
path = "/"

[access.teams]
arewewebyet = "maintain"

[[rulesets]]
pattern = 'master'

[environments.github-pages]
