org = "rust-lang"
name = "blog.rust-lang.org"
description = "Home of the Rust and Inside Rust blogs"
homepage = "https://blog.rust-lang.org"
bots = ["rustbot", "renovate"]

[access.teams]
inside-rust-reviewers = "write"
website = "maintain"
# For Rust release blog posts
release = "write"

[[rulesets]]
pattern = "main"
ci-checks = [
    "lint",
    "build",
]
require-conversation-resolution = true
# Allow promote release to push without PRs
allowed-merge-apps = ["promote-release"]

[environments.github-pages]
branches = ["main"]
