org = "rust-lang"
name = "cargo"
description = "The Rust package manager"
homepage = "https://doc.rust-lang.org/cargo"
bots = ["rustbot", "rfcbot", "renovate"]

[pages]
build-type = "workflow"

[access.teams]
cargo = "write"

[[rulesets]]
pattern = "master"
ci-checks = ["conclusion"]
merge-queue = { enabled = true }

[[rulesets]]
pattern = "rust-1.*"
ci-checks = ["conclusion"]
prevent-creation = false

[[rulesets]]
name = "Only allow the release process to publish tags"
pattern = "0.*"
target = "tag"
pr-required = false
bypass-apps = ["promote-release"]
prevent-update = true

[[crates-io]]
crates = [
    "build-rs",
    "cargo",
    "cargo-credential",
    "cargo-credential-1password",
    "cargo-credential-gnome-secret",
    "cargo-credential-libsecret",
    "cargo-credential-macos-keychain",
    "cargo-credential-wincred",
    "cargo-platform",
    "cargo-test-macro",
    "cargo-test-support",
    "cargo-util",
    "cargo-util-schemas",
    "cargo-util-terminal",
    "crates-io",
    "home",
    "rustfix",
]
publish-workflow = "release.yml"
publish-environment = "release"

[environments.github-pages]

[environments.release]
tags = ["*"]
