org = "rust-lang"
name = "cargo"
description = "The Rust package manager"
homepage = "https://doc.rust-lang.org/cargo"
bots = ["rustbot", "rfcbot", "renovate"]

[access.teams]
cargo = "write"

[[branch-protections]]
pattern = "master"
ci-checks = ["conclusion"]
merge-queue = { enabled = true }

[[branch-protections]]
pattern = "rust-1.*"
ci-checks = ["conclusion"]
prevent-creation = false

[[branch-protections]]
name = "Only allow the release process to publish tags"
pattern = "0.*"
target = "tag"
pr-required = false
allowed-merge-apps = ["promote-release"]
prevent-update = true

[environments.github-pages]

[environments.release]
tags = ["*"]
