org = "rust-lang"
name = "ci-mirrors"
description = "Upload files to Rust's CI mirrors"
homepage = "https://ci-mirrors.rust-lang.org"
bots = []

[access.teams]
infra = "write"

[[rulesets]]
pattern = "main"
ci-checks = ["Build finished"]
dismiss-stale-review = true
merge-queue = { enabled = true, max-entries-to-build = 1, min-entries-to-merge-wait-minutes = 1, max-entries-to-merge = 15 }

[environments.upload]
