org = "rust-lang"
name = "compiler-builtins"
description = "Rust implementations of compiler-rt and libm"
bots = ["rustbot", "forking-renovate"]

[access.teams]
crate-maintainers = "maintain"

[[branch-protections]]
pattern = "main"
ci-checks = ["success"]
required-approvals = 0

[environments.rustc-pull]
branches = ["main"]

[environments.publish]
branches = ["main"]

[[crates-io]]
crates = ["libm"]
publish-workflow = "publish.yaml"
publish-environment = "publish"
teams = ["libs"]
