org = "rust-lang"
name = "fls"
description = "The FLS"
homepage = "https://rust-lang.github.io/fls"
bots = ["rustbot", "rfcbot"]

[access.teams]
fls = "write"
fls-contributors = "triage"
lang = "write"
lang-docs = "write"
lang-ops = "write"
spec = "write"
spec-contributors = "triage"

[[rulesets]]
pattern = "main"
ci-checks = ["CI finished"]
merge-queue = { enabled = true, max-entries-to-build = 1, min-entries-to-merge-wait-minutes = 1 }

[environments.github-pages]
branches = ["gh-readonly-queue/main/*", "main"]
