org = "rust-lang"
name = "futures-rs"
description = "Zero-cost asynchronous programming in Rust"
homepage = "https://rust-lang.github.io/futures-rs/"
bots = ["rustbot"]

[pages]
build-type = "legacy"
branch = "gh-pages"
path = "/"

[access.teams]
wg-async = "write"

[[rulesets]]
pattern = "main"
required-approvals = 0

[environments.github-pages]

[environments.publish]
branches = ["main"]

[[crates-io]]
crates = [
    "futures",
    "futures-channel",
    "futures-core",
    "futures-executor",
    "futures-io",
    "futures-macro",
    "futures-sink",
    "futures-task",
    "futures-test",
    "futures-util",
]
publish-workflow = "publish.yml"
publish-environment = "publish"
teams = ["wg-async"]
