org = "rust-lang"
name = "gha-self-hosted"
description = "GitHub Actions self-hosted runners infrastructure"
bots = []

[access.teams]
infra = "write"

[[rulesets]]
pattern = "main"
ci-checks = ["CI finished"]
merge-queue = { enabled = true, max-entries-to-build = 1, min-entries-to-merge-wait-minutes = 1, max-entries-to-merge = 1 }

[environments.upload]
