org = "rust-lang"
name = "goals"
description = "Rust Project Goals tracker"
homepage = "https://rust-lang.github.io/goals/"
bots = ["rustbot", "rfcbot"]

[pages]
build-type = "workflow"

[access.teams]
lang = "maintain"
lang-ops = "maintain"
lang-docs = "maintain"
types = "maintain"
release = "maintain"
leadership-council = "maintain"
libs = "maintain"
edition = "maintain"
goals = "maintain"
goal-owners = "maintain"

[environments.github-pages]
branches = ["main"]
