org = "rust-lang"
name = "hashbrown"
description = "Rust port of Google's SwissTable hash map"
homepage = "https://rust-lang.github.io/hashbrown"
bots = []

[access.teams]
libs = "write"
libs-contributors = "write"

[[branch-protections]]
pattern = "main"
ci-checks = ["conclusion"]
required-approvals = 0
merge-queue = { enabled = true }

[environments.github-pages]
