org = 'rust-lang'
name = 'libc'
description = 'Raw bindings to platform APIs for Rust'
homepage = "https://docs.rs/libc"
bots = [
    'rustbot',
]

[pages]
build-type = "legacy"
branch = "gh-pages"
path = "/"

[access.teams]
crate-maintainers = 'maintain'

[[rulesets]]
pattern = 'main'
ci-checks = ['success']
required-approvals = 0
merge-queue = { enabled = true, method = "rebase" }
require-linear-history = true

[[rulesets]]
pattern = 'libc-0.2'
ci-checks = ['success']
required-approvals = 0
merge-queue = { enabled = true, method = "rebase" }
require-linear-history = true

[environments.github-pages]
branches = ["gh-pages", "main", "master"]
