org = "rust-lang"
name = "odht"
description = "An on-disk hash table implementation"
bots = []

[access.teams]
compiler = "write"

[[rulesets]]
pattern = "main"
ci-checks = ["Required Checks Passed"]
require-up-to-date-branches = true
require-linear-history = true
