org = "rust-lang"
name = "project-const-generics"
description = ""
homepage = "https://rust-lang.github.io/project-const-generics/"
bots = ["rustbot"]

[access.teams]
project-const-generics = "maintain"
all = "write"

[environments.github-pages]

