org = "rust-lang"
name = "rustc_public"
description = "Define compiler intermediate representation usable by external tools"
bots = ["rustbot"]

[access.teams]
project-rustc-public = "write"

[[rulesets]]
pattern = "main"

[environments.github-pages]
