org = "rust-lang"
name = "rustdoc-types"
description = "Rustdoc's JSON output interface"
bots = ["rustbot"]

[access.teams]
rustdoc = "write"

[environments.publish]
branches = ["trunk"]

[[crates-io]]
crates = ["rustdoc-types"]
publish-workflow = "release.yml"
publish-environment = "publish"

