org = "rust-lang"
name = "rustup"
description = "The Rust toolchain installer"
homepage = "https://rustup.rs/"
bots = ["rustbot", "renovate"]

[pages]
build-type = "legacy"
branch = "gh-pages"
path = "/"

[access.teams]
rustup = "maintain"

[[rulesets]]
pattern = "main"
ci-checks = ["conclusion"]
merge-queue = { enabled = true, method = "rebase" }

[[rulesets]]
pattern = "release/*"
ci-checks = ["conclusion"]
required-approvals = 0
prevent-creation = false

[environments.github-pages]

[environments.www-deploy]
branches = ["www"]
