name: Check Untracked Repositories

on:
  schedule:
    # Every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  check-untracked-repos:
    name: Check untracked repositories
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Rust stable
        uses: ./.github/actions/setup-rust

      - name: Check for untracked repositories
        shell: bash
        run: |
          cargo build --release
          ./target/release/rust-team ci check-untracked-repos

  notify-infra:
    name: Notify the infrastructure team
    needs: [ check-untracked-repos ]
    if: ${{ !cancelled() && needs.check-untracked-repos.result == 'failure' }}
    runs-on: ubuntu-latest
    environment: deploy
    steps:
      - name: Send Zulip message
        uses: zulip/github-actions-zulip/send-message@f675f2b4eb2a95fae974215476dcb7ad8dfeff6b # v2.0.2
        with:
          api-key: ${{ secrets.ZULIP_API_TOKEN }}
          email: ${{ secrets.ZULIP_USERNAME }}
          organization-url: "https://rust-lang.zulipchat.com"
          to: "t-infra"
          type: "stream"
          topic: "Untracked repositories"
          content: |
            The untracked repositories workflow failed.
            Check out the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}).
