name: Check Untracked Repositories

on:
  schedule:
    # Every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions: {}

jobs:
  check-untracked-repos:
    name: Check untracked repositories
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Rust stable
        uses: ./.github/actions/setup-rust

      - name: Check for untracked repositories
        shell: bash
        run: |
          cargo build --release
          ./target/release/rust-team ci check-untracked-repos
